### PR TITLE
[Blacklist] More idiomatic CLAide usage

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
\c @dbgrandi

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by dbgrandi** [comment]
Thanks, @segiddins! It took me a while to figure out that this was not changing the behavior.

**Comment by dbgrandi** [comment]
I'll add you to the contributors list in the README but, unfortunately, I can't add contributors to the repo.

**Comment by segiddins** [comment]
No worries, just stumbled upon the repo last night when I was procrastinating :)

**Pull request merged**
